package com.project.thelibrarians_lso2324.activities;

import android.app.Dialog;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;


import com.project.thelibrarians_lso2324.Domain.CardBookPropertyDomain;
import com.project.thelibrarians_lso2324.R;
import com.project.thelibrarians_lso2324.adapters.RecommendedAdapter;

import java.util.ArrayList;



public class HomePageActivity extends AppCompatActivity {
    private RecyclerView.Adapter adapterRecommended;
    private  RecyclerView recyclerViewPopular,recyclerViewNewReleases;
    private ImageButton FilterButton;
    private CardBookPropertyDomain object;
    private TextView SeeAll,SeeAll2;
    private ImageButton imageButtonLove;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.adminhomepage);

        //set underline for TextViewSeeAll
        SeeAll = findViewById(R.id.TextViewSeeAll);
        SeeAll.setPaintFlags(SeeAll.getPaintFlags() |   android.graphics.Paint.UNDERLINE_TEXT_FLAG);

        //set underline for TextViewSeeAll2
        SeeAll2 = findViewById(R.id.TextViewSeeAll2);
        SeeAll2.setPaintFlags(SeeAll2.getPaintFlags() |   android.graphics.Paint.UNDERLINE_TEXT_FLAG);


        //Navigate to LoveBook
        imageButtonLove = findViewById(R.id.imageButtonLove);
        imageButtonLove.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(HomePageActivity.this, LoveBook.class);
                startActivity(intent);
                finish();
            }
        });

        //Navigate to SeeAllBooks
        SeeAll = findViewById(R.id.TextViewSeeAll);
        SeeAll2 = findViewById(R.id.TextViewSeeAll2);
        SeeAll.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(HomePageActivity.this, AllBookPage.class);
                startActivity(intent);
                finish();
            }
        });
        SeeAll2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(HomePageActivity.this, AllBookPage.class);
                startActivity(intent);
                finish();
            }
        });



        //Add element in the recycler view
        initRecyclerview();

        //Navigate to AddBook
        ImageButton AddBookButton = findViewById(R.id.AddBook_button);
        AddBookButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(HomePageActivity.this, AddBookActivity.class);
                startActivity(intent);
                finish();
            }
        });

        //Views filter menu
        FilterButton = findViewById(R.id.imageButtonFilter);
        FilterButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                showDialog();
            }

            private void showDialog() {
                final Dialog dialog = new Dialog(HomePageActivity.this);
                dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
                dialog.setContentView(R.layout.activity_filter_menu);
                dialog.show();
                dialog.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
                dialog.getWindow().getAttributes().windowAnimations = R.style.DialogAnimation;
                dialog.getWindow().setGravity(Gravity.BOTTOM);
                Button AddFilterButton = dialog.findViewById(R.id.AddFilterButton);
                AddFilterButton.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        dialog.dismiss();
                    }
                });


            }
        });

        }

    private void initRecyclerview() {
        ArrayList<CardBookPropertyDomain> itemsPopularBooks = new ArrayList<>();
        ArrayList<CardBookPropertyDomain> itemsNewReleases = new ArrayList<>();

        itemsPopularBooks.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsPopularBooks.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));


        recyclerViewPopular= findViewById(R.id.recyclerViewMostPopularBooks);
        recyclerViewPopular.setLayoutManager(new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false));
        adapterRecommended = new RecommendedAdapter(itemsPopularBooks);
        recyclerViewPopular.setAdapter(adapterRecommended);


        object = (CardBookPropertyDomain) getIntent().getSerializableExtra("object");
        if (object!= null)  {
            itemsNewReleases.add(new CardBookPropertyDomain(object.getTitle(),object.getAuthor(),object.getISBN(),object.getCategory(),"pic1",object.getDescription(),object.getTotalCopies(),object.getAvailableCopies(),object.getCopiesInUse()));
        }

        itemsNewReleases.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("Il bosco di nebbia","Gabriella Genisi","AQ23457789087","Thriller","pic1","Lolita Lobosco è stata promossa questore e deve trasferirsi a Padova. Ma gli inizi non sono facili: l'ambiente si rivela più intollerante del previsto, la nebbia confonde i pensieri e mortifica i capelli, l'orizzonte d'acqua di Bari è troppo lontano per curare la solitudine. Anche il lavoro stenta a decollare, e poi, con i nuovi colleghi, proprio non riesce a legare. Solo grazie all'aiuto e ai consigli di Giancarlo Caruso, affascinante vicequestore di origini siciliane, le cose migliorano, mentre un caso di bullismo - la scomparsa, nell'omertà generale, di un ragazzo da uno dei licei più in vista della città del Santo - mette a dura prova il talento investigativo di Lolì. Dopo tanto freddo, intorno e nell'anima, la commissaria più bella del Mediterraneo riesce finalmente a farsi richiamare nella sua amata Puglia, dove pure l'attende un mistero da risolvere: una sensuale arpista è stata massacrata in un appartamento. I sospetti sono tanti, ma c'è uno strano testimone... Alle due estremità della penisola, tra panzerotti e pettole di Natale, la passionale poliziotta barese torna a ricercare la verità, sui luoghi di delitti efferati e nel fondo stropicciato del proprio cuore.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("La principessa Angina","Roland Tapor","9788899729554","Historical novel","pic2","Angina è una piccola principessa che ha dovuto abbandonare il suo regno per le perfide trame dei nemici della Corona, e ora è in viaggio alla ricerca di uno zio lontano, su un furgone a forma di elefante con il fido cancelliere, vecchio poeta ubriacone, e Jonathan, ragazzo raccolto per strada che si unisce suo malgrado alla strampalata spedizione. Ma ha poco senso accennare alla trama. Così come ha poco senso parlare di fiaba, di racconto nero, di satira di costume o anche – come fa l’autore nella prima pagina, per depistarci – di cronaca metaforica di una malattia: perché è proprio il non-senso il senso del libro. La principessa Angina è un romanzo fantastico che pare scaturire dalla fantasia sfrenata di un bambino, priva di filtri o schemi prestabiliti; è un gioco stravagante con accadimenti e situazioni buffe, ma anche con scherzi e capriole testuali; è un immenso territorio dell’immaginario dove persino le illustrazioni e gli effetti grafici non sono meri ornamenti ma deliziose estensioni della storia… e della follia creativa dell’autore. La principessa Angina, in definitiva, altro non è che un inno alla libertà artistica come insopprimibile e inarrestabile istinto vitale.",5,3,2));
        itemsNewReleases.add(new CardBookPropertyDomain("The power of balance ","William R.Torbert","080394067X","Economic management","pic3","Presentando una nuova teoria del potere, una nuova pratica di gestione e una nuova teoria delle scienze sociali, questo volume contraddice i seguenti luoghi comuni: che tutto il potere corrompe; che ogni struttura organizzativa limita; e che le scienze sociali sono più pure quanto più sono separate dall'azione. Torbert presenta una concettualizzazione del potere che genera produttività, giustizia e indagine; sviluppa una teoria della struttura liberante attraverso la quale le organizzazioni possono generare un miglioramento continuo della qualità; e introduce un nuovo paradigma delle scienze sociali coinvolte - l'azione di ricerca.",5,3,2));

        recyclerViewNewReleases= findViewById(R.id.recyclerViewNewReleasesBooks);
        recyclerViewNewReleases.setLayoutManager(new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false));
        adapterRecommended = new RecommendedAdapter(itemsNewReleases);
        recyclerViewNewReleases.setAdapter(adapterRecommended);
    }
}
