version: '3.9'

services:
  server-c:
    container_name: server-c
    restart: on-failure
    build: server/.
    ports:
      - "80:4040"
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "42069:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=thelibrariansDB
      - TZ=Europe/Rome
      - PGTZ=Europe/Rome
    volumes:
      - /home/antonio/Scrivania/sql-scripts:/docker-entrypoint-initdb.d
