package com.project.thelibrarians_lso2324.model;

public enum BookGenre {

    FANTASCIENZA,
    FANTASY,
    ROMANZO_STORICO,
    THRILLER,
    HORROR,
    ROMANTICO,
    GIALLO,
    AVVENTURA,
    FANTASY_URBANO,
    FANTASY_EPICO,
    FAVOLA,
    FANTASY_SCIENTIFICO,
    DRAMMATICO,
    BIOGRAFICO,
    SAGGIO,
    SAGGIO_FILOSOFICO,
    POESIA,
    COMMEDIA,
    SATIRA,
    AZIONE, SCONOSCIUTO,
}
